name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            file: target/release/intersystems-ls
            target: linux-x86_64
          - os: windows-latest
            file: target/release/intersystems-ls.exe
            target: windows-x86_64
          - os: macos-latest
            file: target/release/intersystems-ls
            target: darwin-x86_64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: caretdev/rust-irisnative
          token: ${{ secrets.TOKEN_GITHUB }}
          path: crates/rust-irisnative
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --bins --release --locked
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: ${{ matrix.file }}
  combine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - run: ls -laR
